/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_niotong_jnitest_getJniString */

#ifndef _Included_com_niotong_jnitest_getJniString
#define _Included_com_niotong_jnitest_getJniString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_niotong_jnitest_getJniString
 * Method:    getStringCPP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_niotong_jnitest_getJniString_getStringCPP
  (JNIEnv *, jclass);

/*
 * Class:     com_niotong_jnitest_getJniString
 * Method:    getStringJave
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_niotong_jnitest_getJniString_getStringJave
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
