/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_niotong_tester_JniTest */

#ifndef _Included_com_niotong_tester_JniTest
#define _Included_com_niotong_tester_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_niotong_tester_JniTest
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_niotong_tester_JniTest_add
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
